systemLog:
  destination: file
  path: /mongo-shard-test/data/logs/config.log
storage:
  dbPath: /mongo-shard-test/data/config
net:
  bindIp: 127.0.0.1
  port: 27020
sharding:
  clusterRole: configsvr
replication:
  replSetName: configReplSet
