systemLog:
  destination: file
  path: /mongo-shard-test/data/logs/shard1.log
storage:
  dbPath: /mongo-shard-test/data/shard1
net:
  bindIp: 127.0.0.1
  port: 27018
sharding:
  clusterRole: shardsvr
replication:
  replSetName: shard1ReplSet
